name: "Simple Commit and Push"

author: "ryohidaka"

description: "GitHub Actions for commiting & pushing to GitHub repository local changes."

branding:
  color: green
  icon: send

inputs:

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set GitHub Path
      run: echo "GITHUB_ACTION_PATH=${GITHUB_ACTION_PATH}" >> $GITHUB_ENV
      shell: bash
