name: "Simple Commit and Push"

author: "ryohidaka"

description: "GitHub Actions for commiting & pushing to GitHub repository local changes."

branding:
  color: green
  icon: send

inputs:
  commit-user-name:
    required: false
    default: "GitHub Actions"
    description: "Commit username. Defaults to 'GitHub Actions'."

  commit-user-email:
    required: false
    default: "actions@github.com"
    description: "Commit email. Defaults to 'actions@github.com'."

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set GitHub Path
      run: echo "GITHUB_ACTION_PATH=${GITHUB_ACTION_PATH}" >> $GITHUB_ENV
      shell: bash

    - name: Set Git Config
      run: |
        $GITHUB_ACTION_PATH/scripts/set_config.sh \
          "${{ inputs.commit-user-name }}" \
          "${{ inputs.commit-user-email }}"
      shell: bash
