name: "Simple Commit and Push"

author: "ryohidaka"

description: "GitHub Actions for commiting & pushing to GitHub repository local changes."

branding:
  color: green
  icon: send

inputs:
  files:
    description: "Files to commit. Defaults to '.'."
    required: false
    default: "."

  commit-user-name:
    required: false
    default: "GitHub Actions"
    description: "Commit username. Defaults to 'GitHub Actions'."

  commit-user-email:
    required: false
    default: "actions@github.com"
    description: "Commit email. Defaults to 'actions@github.com'."

  commit-message:
    required: false
    default: "chore: autopublish"
    description: "Commit message. Defaults to 'chore: autopublish'."

  dry-run:
    required: false
    default: "false"
    description: "If true, the push steps will be skipped. Defaults to 'false'"

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set GitHub Path
      run: echo "GITHUB_ACTION_PATH=${GITHUB_ACTION_PATH}" >> $GITHUB_ENV
      shell: bash

    - name: Set Git Config
      run: |
        $GITHUB_ACTION_PATH/scripts/set_config.sh \
          "${{ inputs.commit-user-name }}" \
          "${{ inputs.commit-user-email }}"
      shell: bash

    - name: Staging And Check Diff
      id: check_diff
      run: |
        $GITHUB_ACTION_PATH/scripts/check_diff.sh \
          "${{ inputs.files }}"
      shell: bash

    - name: Commit
      if: steps.check_diff.outcome != 'success' # Skip if no changes
      run: |
        $GITHUB_ACTION_PATH/scripts/commit.sh \
          "${{ inputs.commit-message }}"
      shell: bash

    - name: Push
      if: steps.check_diff.outcome != 'success' && inputs.dry-run == 'false' # Skip if no changes
      run: |
        $GITHUB_ACTION_PATH/scripts/push.sh
      shell: bash
